language: go
go:
- 1.4
- 1.5
- 1.6
- 1.7
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get gopkg.in/check.v1
- go get github.com/droundy/goopt
- go get github.com/alyu/configparser
- go get github.com/aliyun/aliyun-oss-go-sdk/oss
script:
- cd lib
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
